### ISSUE TITLE
[Feature]  Class and Property Decorators

### ISSUE THREAD

**Issue by alexgwolff** [chakra-core/ChakraCore#2970]
### Introduction

> Decorators offer a convenient declarative syntax to modify the shape of class declarations. This capability can be used for myriad purposes including modifying the descriptor of the declared member (@nonconfigurable/@enumerable), adding metadata (as used by Angular), and more. [Source](http://tc39.github.io/proposal-decorators/)

_**Example**_:
```javascript 
@frozen class Foo {
  @configurable(false) @enumerable(true) method() {
     //do something
  }
}
```
__Current Stage__ : 2
__Latest spec__: https://tc39.github.io/proposal-decorators/

**Comment by digitalinfinity** [comment]
cc @bterlson

**Comment by alexgwolff** [comment]
any progress?

**Comment by digitalinfinity** [comment]
Hi @alexgwolff - no, I don't believe we have any updates regarding this proposal. However, we do accept PRs 😄
