### ISSUE TITLE
Refactor bytecode regen scripts

### ISSUE THREAD

**Issue by dilijev** [chakra-core/ChakraCore#3330]
* Move to `tools/*/<scripts>`
* Reduce duplication.

See https://github.com/Microsoft/ChakraCore/pull/3323#discussion_r127020344

**Comment by Cellule** [comment]
Feature suggestion: Give option to regen only 1 architecture at a time for when we're in active development and don't care about rebuilding everything until we're satisfied with the result.

**Comment by dilijev** [comment]
@Cellule the first draft of the script I ended up publishing was derived from a script which regen's only one. I meant to make that detect and regen the active config (e.g. x64_debug) when the right environment variables are set.

I think we should make the GenByteCode script regen only one (rather than a pair) and have the parameters control the rest and update the other scripts to call it more times as necessary.

It seems kind of silly that the solution here basically ends up being a utility script to call a script which more or less does what you want, but to automatically pass the needed parameters.
