### ISSUE TITLE
Unhelpful Error Message - Should be missing 'async' keyword instead of Expected ';'

### ISSUE THREAD

**Issue by michael-hawker** [chakra-core/ChakraCore#5103]
(Originally reported through VS forum, told to report here instead.)

If I have the following JavaScript Vue.js code in a UWP app:

```
    EventBus.$on("erase-history", (event) => {
        await clearCacheAsync().then(() => console.log("Cleared Cache"), (e) => console.error(`Error Clearing Cache ${e}`));
    });
```

Then I get an error message running my app:

    JavaScript critical error at line 94, column 19 in ms-appx://js/mycode.js \n\nSCRIPT1004: Expected ';'

(that's the line with the await on it)

The real problem is I'm missing the 'async' keyword on the line before:

    EventBus.$on("erase-history", async (event) => {

So my error message should be 'Expected async' to actually tell me what the real problem is. As otherwise, I look at semi-colons and I have nothing wrong.

**Comment by jackhorton** [comment]
Agreed, that's a pretty lackluster error message. I imagine its because outside of async functions, await is treated like any other identifier name, so `function () { await call() }` no different than saying `function () { x call() }`. With that being said, Firefox seems to special-case this and provides a much better error as a result.

**Comment by rhuanjl** [comment]
This relates to the use of ERRnoSemic in Parse.cpp there are only 4 uses of that in the file - to fix this would need to determine which one is hit in this case and precede it with a special case to check for `await` - should be fairly easy thing to do, hence marking as a good first issue.

**Comment by hez2010** [comment]
Without `async` context `await` should not be a keyword, which means that you can declare a function or variable named `await` and invoke it without problem.
```javascript
var await = function (a) { ... }
await(123); // it's ok in non-async context
```
I think the error message should be "missing (" but not "missing ;" or "missing async".

**Comment by rhuanjl** [comment]
Indeed the `await` token outside of an async function is parsed as an identifier not a keyword BUT the suggestion here is that it is probably intended by the developer as a keyword and they forgot to make the function async - hence detecting it specifically would be useful.

It actually shouldn't be too hard to do, when the error is thrown the Parser will be sitting on the token after the the await so should be able to step back one token, check if it is an identifier, if it is, compare specifically against "await" and throw a specific error for it something like `"await" is not a keyword outside of an async function`.

**Comment by ylukomskyi** [comment]
Would like to try fixing this issue. Is anyone working on it at the moment?

**Comment by rhuanjl** [comment]
@ylukomskyi no one else has claimed it, feel free to give it a go.

**Comment by cavishek39** [comment]
Hi, @ylukomskyi are you still working on it? If not then should I give it a try?

**Comment by ylukomskyi** [comment]
Hi @cavishek39, i am not working on this atm, give it a try
