### ISSUE TITLE
Chakra should throw an exception when evaluate an invalid "for" statement

### ISSUE THREAD

**Issue by igor-simoes** [chakra-core/ChakraCore#5128]
Hi everyone,
I found an inconsistency when try to evaluate a "for" statement without the body statement.

OS: Ubuntu 16.04 x64
Chakra: 1.10.0.0-beta

Step to reproduce:
```
first = "for (i = 0; i < 3; i++);"
print (eval ( first ) )

second = "for (i = 0; i < 3; i++)"
print (eval ( second ) )
```
Actual results:
```
undefined
undefined
```
Expected results:
```
undefined
SyntaxError: Unexpected end of input
```
I ran the second statement without  `eval` function and Chakra passes without throw an Exception also.
```
for (i = 0; i < 3; i++)
```
V8, SpiderMonkey and JavascriptCore works as expected.

cinfuzz

**Comment by fatcerberus** [comment]
Sounds like overzealous ASI.

**Comment by infinnie** [comment]
Reproduced on Edge.
OS: Windows
User agent:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
```

**Comment by rhuanjl** [comment]
Was thinking of trying to fix this but first I took a quick look at it with eshost:
Firstly without eval none of the 4 throw an error:
```
# Source
for(var i = 0; i < 10; ++i)

#### Chakra, JavaScriptCore, SpiderMonkey, V8 --harmony

```
Then with eval CC still throws no error but the others do throw errors:

```
## Source
eval("for(var i = 0; i < 10; ++i)");

#### Chakra


#### V8 --harmony
SyntaxError: Unexpected end of input

#### SpiderMonkey
SyntaxError: expected expression, got end of script:

#### JavaScriptCore
SyntaxError: Unexpected end of script
```
It seems that with no eval present all 4 engines happily apply ASI  whereas without an eval only CC applies ASI - IMO CC's behaviour seems more logical than the other 3 engines here. I don't know the correct answer per spec though; but for now I won't submit a "fix" as not confident that current behaviour is wrong.

**Comment by fatcerberus** [comment]
I don’t think ASI should apply here at all: if you put the offending code into a function block then all engines will produce a syntax error.
