### ISSUE TITLE
Test262 Agent feature request: $262.agent.monotonicNow()

### ISSUE THREAD

**Issue by rwaldron** [chakra-core/ChakraCore#5271]
Hello!

I've been trying my own hand at implementing `$262.agent.monotonicNow()` (as a function exposed on `WScript` when `-Test262` is used), which is necessary for testing Atomic operations that involve wait/wake with specified timeouts. I was attempting to use `std::chrono::steady_clock` with the appropriate included, but that results in the following `no member named 'PAL_ctime' in the global namespace`. I'm all out of ideas :|

**Comment by digitalinfinity** [comment]
hi @rwaldron - for a variety of reasons, we implement our own versions of some CRT functions by using a library called PAL that we forked from the CoreCLR when we were adding Linux/macOS support. It does some unsavory things with functions such as ctime. Take a look at pal/src/include/pal/palinternal.h and maybe pal/src/cruntime/misctls.cpp to make sure that the latter is actually being compiled. I suspect the answer might be as simple as defining PAL_ctime in pal/inc/pal.h but if it's not, maybe this information gives you some hints. If you still need help, can you point me to a branch and I can take a look.

**Comment by rwaldron** [comment]
@digitalinfinity thanks for the support and advice! I will get back to you as soon as I have a chance to follow these leads.

**Comment by rwaldron** [comment]
> Take a look at pal/src/include/pal/palinternal.h 

```cpp
#undef ctime
```

If I remove that line, I get the same error:


```
In file included from /Users/rwaldron/clonez/ChakraCore/bin/ch/WScriptJsrt.cpp:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:66:9: error: no member named 'PAL_ctime' in the global namespace
using ::ctime;
      ~~^
/Users/rwaldron/clonez/ChakraCore/pal/inc/pal.h:6096:23: note: expanded from macro 'ctime'
#define ctime         PAL_ctime
                      ^
1 error generated.
```

I checked pal/src/cruntime/misctls.cpp, and [`PAL_ctime( const PAL_time_t *clock )`](https://github.com/Microsoft/ChakraCore/blob/master/pal/src/cruntime/misctls.cpp#L88-L130) is defined, however it's not defined in pal/inc/pal.h. It's not yet clear to me where PAL_ctime should be added in pal/inc/pal.h, but I'll work on it a bit more and report back (any additional tips/pointers are welcome!)
