### ISSUE TITLE
Ubuntu 20.04, Clang 10 build failure

### ISSUE THREAD

**Issue by LaloSteinmann** [chakra-core/ChakraCore#6466]
I tried to compile ChakraCore in Ubuntu 20.04 following the build instructions for Linux.

I got below error. I follow same procedure in Ubuntu 16.04 and I was able to compile without any issue. Any clue about below error? 

Thank you!

-- Configuring done
-- Generating done
-- Build files have been written to: /home/AzureUser/Desarrollo/ChakraCore/out/Debug
[  1%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.Singular.dir/cruntime/file.cpp.o
In file included from /home/AzureUser/Desarrollo/ChakraCore/pal/src/cruntime/file.cpp:23:
In file included from /home/AzureUser/Desarrollo/ChakraCore/pal/src/include/pal/palinternal.h:553:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/stdlib.h:36:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cstdlib:75:
/usr/include/stdlib.h:112:36: error: exception specification in declaration does not match previous declaration
__extension__ extern long long int atoll (const char *__nptr)
                                   ^
/home/AzureUser/Desarrollo/ChakraCore/pal/inc/pal.h:6198:33: note: previous declaration is here
PALIMPORT long long int __cdecl atoll(const char *);
                                ^
1 error generated.
make[2]: *** [pal/src/CMakeFiles/Chakra.Pal.Singular.dir/build.make:63: pal/src/CMakeFiles/Chakra.Pal.Singular.dir/cruntime/file.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:757: pal/src/CMakeFiles/Chakra.Pal.Singular.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
See error details above. Exit code was 2

**Comment by rhuanjl** [comment]
What version of ChakraCore are you trying to build? Latest master or the 1.11 release branch?

**Comment by LaloSteinmann** [comment]
I'm using the latest master in both cases.(16.04, ok,  and 20.04, failed) I have not tried with 19.04, I'll do that tomorrow.

**Comment by rhuanjl** [comment]
One other possibility is that it could relate to this fix which we have not (yet) ported across from coreCLR for PAL - https://github.com/dotnet/coreclr/pull/28045 - this may cause a build failure with clang 10, though shouldn't affect clang 9 or earlier.

**Comment by rhuanjl** [comment]
@Fly-Style confirmed that he can build master on Ubuntu 20.04 with clang 9.

**Comment by LaloSteinmann** [comment]
I believe I tried clang 10, I'd try clang 9

**Comment by LaloSteinmann** [comment]
I confirm that clang 9 works ok in Ubuntu 20.04. The issue was more related to clang10 and I guess PAL

**Comment by rhuanjl** [comment]
Fixed in #6604 

(Sorry for delay I forgot about this)
