### ISSUE TITLE
build problems：What should I do? can you give me some suggestions?

### ISSUE THREAD

**Issue by 1789120321** [chakra-core/ChakraCore#6501]
./build.sh
Searching for Clang...
Clang++ found at /usr/bin/clang++
Compile Target : amd64
Generating Release makefiles
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lenovo/Desktop/ChakraCore-1.4.1/BuildLinux/Release
[  0%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/file.cpp.o
In file included from /home/lenovo/Desktop/ChakraCore-1.4.1/pal/src/cruntime/file.cpp:23:
In file included from /home/lenovo/Desktop/ChakraCore-1.4.1/pal/src/include/pal/palinternal.h:334:
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal.h:3382:59: error: unknown type name 'KNONVOLATILE_CONTEXT_POINTERS'
PALIMPORT BOOL PALAPI PAL_VirtualUnwind(CONTEXT *context, KNONVOLATILE_CONTEXT_POINTERS *contextPointers);
                                                          ^
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal.h:3385:50: error: unknown type name 'KNONVOLATILE_CONTEXT_POINTERS'
                                                 KNONVOLATILE_CONTEXT_POINTERS *contextPointers,
                                                 ^
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal.h:6999:36: error: implicit conversion from 'unsigned long long' to 'const SIZE_T' (aka 'const unsigned long') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
    const SIZE_T NoTargetFrameSp = SIZE_MAX;
                                 ~ ^~~~~~~~
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal_mstypes.h:327:18: note: expanded from macro 'SIZE_MAX'
#define SIZE_MAX _UI64_MAX
                 ^~~~~~~~~
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal.h:394:23: note: expanded from macro '_UI64_MAX'
#define _UI64_MAX     UI64(0xffffffffffffffff)
                      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal_mstypes.h:160:24: note: expanded from macro 'UI64'
#define UI64(x)        UI64_HELPER(x)
                       ^~~~~~~~~~~~~~
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal_mstypes.h:159:24: note: expanded from macro 'UI64_HELPER'
#define UI64_HELPER(x) x ## ULL
                       ^~~~~~~~
<scratch space>:2:1: note: expanded from here
0xffffffffffffffffULL
^~~~~~~~~~~~~~~~~~~~~
In file included from /home/lenovo/Desktop/ChakraCore-1.4.1/pal/src/cruntime/file.cpp:25:
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/src/include/pal/file.h:279:16: error: functions that differ only in their return type cannot be overloaded
size_t __cdecl PAL_fwrite(const void *pvBuffer, size_t nSize, size_t nCount, PAL_FILE *pf);
~~~~~~         ^
/home/lenovo/Desktop/ChakraCore-1.4.1/pal/inc/pal.h:6703:26: note: previous declaration is here
PALIMPORT size_t __cdecl PAL_fwrite(const void *, size_t, size_t, PAL_FILE *);
          ~~~~~~         ^
4 errors generated.
pal/src/CMakeFiles/Chakra.Pal.dir/build.make:62: recipe for target 'pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/file.cpp.o' failed
make[2]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/file.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'pal/src/CMakeFiles/Chakra.Pal.dir/all' failed
make[1]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
See error details above. Exit code was 2

**Comment by rhuanjl** [comment]
Is this still an issue?
Are you using the latest master branch?
What system are you building on?

**Comment by ppenzin** [comment]
This is 1.4, which is oddly old. Closing since we haven't heard back on this in a while.
