### ISSUE TITLE
An issue about the TypedArray.prototype.sort().

### ISSUE THREAD

**Issue by NWU-NISL** [chakra-core/ChakraCore#6503]
A typeerror occurred in ChakraCore when I passed an undefined parameter in TypedArray.prototype.sort(), but other engines, such as V8 and quickjs, did not throw an error. Therefore, I think there may be a problem here.

**version**

1.11.19

**command**

```javascript
ChakraCore/out/Debug/ch testcase.js
```

**testcase**

```javascript
var NISLFuzzingFunc = function(){
    var a = new Uint32Array(1);
    var b = a.sort(undefined);
}
NISLFuzzingFunc();
```

**output**

```javascript
TypeError:[TypedArray].prototype.sort: argument is not a Function object.
```

**expected behavior**

```javascript
No error occurred.
``` 
Contributor : @Haobin-Lee

**Comment by ppenzin** [comment]
@chicoxyzzy, @zenparsing, how does this look from spec point of view?

**Comment by chicoxyzzy** [comment]
The `compareFn` could be `undefined` in both `Array.prototype.sort` and `%TypedArray%.prototype.sort`. The runtime semantics for the latter is defined in https://tc39.es/ecma262/#sec-%typedarray%.prototype.sort

**Comment by ppenzin** [comment]
Thank you @chicoxyzzy!

@NWU-NISL thank you for the report.

**Comment by ppenzin** [comment]
To re-iterate, the behavior should be to do nothing if the sort function is undefined.

**Comment by chicoxyzzy** [comment]
That's not quite correct. If compare function is `undefined`, then algorithm is

If x and y are both NaN, return +0.
If x is NaN, return 1.
If y is NaN, return -1.
If x < y, return -1.
If x > y, return 1.
If x is -0 and y is +0, return -1.
If x is +0 and y is -0, return 1.
Return +0.

**Comment by ppenzin** [comment]
Thanks @chicoxyzzy! :+1:

**Comment by rhuanjl** [comment]
In TypedArray.prototype.sort currently it behaves correctly if no parameter is provided OR if a usable compare function is provided but it errors if you give `undefined` which it should treat the same as no parameter - bit of an edge case but we should fix I suppose.
