### ISSUE TITLE
A question about defineProperty of Proxy object

### ISSUE THREAD

**Issue by NWU-NISL** [chakra-core/ChakraCore#6505]
When calling `Object.defineProperty` as below, the internal method `[[DefineOwnProperty]]` will be  invoked.

According to ES10.0, when invoking the internal method `[[DefineOwnProperty]]` of the proxy object, the method `defineProperty` of proxy handler is called. So the overwritten property `defineProperty ` below is called. And a false will be returned after using `ToBoolean` dealing with its return value, because the method's default return value is undefined.

Finally, a TypeError will be thrown as other engines(like V8,spiderMonkey and quickjs) do. 

But Chakra didn't throw any error as my expection, Is there any information I have missed?

#### version

```
1.11.19
```

#### command

```
chakra/cc_linux_x64_1_11_19/ChakraCoreFiles/bin/ch testcase.js
```

#### testcase

```javascript
function main() {
var handler = {defineProperty:function(){
        print("overwrite definedProperty");
        }
     };
var target = {"a":3};
var descBefore = Object.getOwnPropertyDescriptor(target,"a");
for(var j in descBefore){
  print(j,descBefore[j]);
	}

var p = new Proxy(target,handler);
var desc = {value:200};
var v21 = Object.defineProperty(p,"a",desc);
print(v21);

var descAfter = Object.getOwnPropertyDescriptor(target,"a");
for(var i in descAfter){
print(i,descAfter[i]);
	}
}
main();
```

#### output

```
value 3
writable true
enumerable true
configurable true
overwrite definedProperty
[object Object]
value 3
writable true
enumerable true
configurable true
```

#### expected output

```
value 3
writable true
enumerable true
configurable true
overwrite definedProperty
TypeError: proxy defineProperty handler returned false for property '"a"'
```

contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by ppenzin** [comment]
ping @zenparsing, @chicoxyzzy

**Comment by rhuanjl** [comment]
This is a bug, per https://tc39.es/ecma262/#sec-definepropertyorthrow if the DefineOwnProperty method of an object (in this case the proxy trap) returns false-ish then should throw.

Should be an easy-ish fix, need to look at the implementation of Object.defineProperty (probably called) EntryDefineProperty and see how it handles calling a false return value.
