### ISSUE TITLE
Assertion failure in JSONStringifier.cpp caused by incorrect type checking

### ISSUE THREAD

**Issue by sunlili** [chakra-core/ChakraCore#6534]
Hello, running following code in ch1.11.24(debug), an assertion will be thrown. 
```
vdate = new Date(1234567890123).getVarDate();
JSON.stringify(vdate, true);
```
output:
```
ASSERTION 28300: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.24\lib\runtime\library\jsonstringifier.cpp, line 745) UNREACHED
 Failure: ((0))
FATAL ERROR: ch.exe failed due to exception code c0000420
```
<img width="865" alt="tmp" src="https://user-images.githubusercontent.com/10752186/102300951-dbc6a000-3f90-11eb-85b3-3ed55d70c71a.png">

`vdate` is a Js::JavascriptVariantDate object, whose typeID is 10. Since TypeIds_VariantDate (10) < TypeIds_LastJavascriptPrimitiveType (21), it isn't be treated as object type in `JavascriptOperators::IsObject(_In_ RecyclableObject* instance)`. 
https://github.com/microsoft/ChakraCore/blob/7d4bdd821d452d6b91a21936257d7e352ea7dc4b/lib/Runtime/Library/JSONStringifier.cpp#L888-L899
Finally, it fails to pass the check in JSONStringifier.cpp:888, 
and go into line 897. In ReadData(), the assertion is triggered.

ISec Lab.
2020.12.16

**Comment by rhuanjl** [comment]
Thanks for the report.

OK, so the `.getVarDate()` method is a Microsoft specific extension not included in the javascript spec, in release builds attempting to stringify a VarDate will return undefined - and that behaviour has been the case for a while. In a Debug build it will assert.

Clearly this shouldn't hit an assertion BUT a few options:
a) edit this so it's treated as a "normal" object
b) edit this so it's treated as a number
c) edit this so it doesn't assert but still returns undefined
d) remove VarDate from the source entirely - it's non-standard

I note there's a high chance that there will be other bugs related to VarDates elsewhere in the source as they're a special type of object that's neither a proper JsObject nor a proper ValueType.

I'm favouring option (d) but want at least a second opinion before going ahead @ppenzin thoughts?

**Comment by ppenzin** [comment]
I am slightly leaning in favor of (d), since it is non-standard. Do we know of anybody depending on it?
