### ISSUE TITLE
Assertion failure in JavascriptOperators::ValidateAndApplyPropertyDescriptor()

### ISSUE THREAD

**Issue by sunlili** [chakra-core/ChakraCore#6536]
Hi, execution following code in ch 1.11.24(debug), an assertion will be thrown.
```
var arr = [1,2,3,4];
var handler = {};
Object.defineProperty(arr, 'length', {
    writable:false
});
p = new Proxy(arr, handler);
Object.prototype.push = Array.prototype.push;
p.push(1);
```
output:
```
ASSERTION 7624: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.24\lib\runtime\language\javascriptoperators.cpp, line 9023) TypedArrayBase::Is(obj)
 Failure: (TypedArrayBase::Is(obj))
FATAL ERROR: ch.exe failed due to exception code c0000420
```
<img width="888" alt="tmp" src="https://user-images.githubusercontent.com/10752186/102314174-f73fa400-3fac-11eb-9358-9bae5db4d004.png">

After redefining the property  'length' of `arr` unwritable, `arr` convert into an ES5Array. However, the assertion think it should handle a TypedArray object.

ISec Lab.
2020.12.16

**Comment by rhuanjl** [comment]
Thanks for the report this was alread fixed in master by this commit: https://github.com/microsoft/ChakraCore/commit/bd1e792671aff0482cb27c558e9b8be8da7dd46e
