### ISSUE TITLE
Assertion failure in BlockActivationObject* FromVar(Var value)

### ISSUE THREAD

**Issue by sunlili** [chakra-core/ChakraCore#6537]
Hello, executing following code, an assertion will be throw.
```
var eval = WScript.LoadScript('', 'samethread').eval;
for (let i = 0; i < 1; i++) {
    eval('for(var x in [1,2,3,4])( /x/ );');
}
```
output:
```
ASSERTION 23500: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.24\lib\runtime\types\activationobject.h, line 65) BlockActivationObject::Is(value)
 Failure: (BlockActivationObject::Is(value))
FATAL ERROR: ch.exe failed due to exception code c0000420
```
<img width="870" alt="tmp" src="https://user-images.githubusercontent.com/10752186/102315366-01fb3880-3faf-11eb-8ce0-ef0c0f7cd875.png">

When handling the bytecode CloneBlockScope of eval, it will get `scope` variable, which is the `value` in assertion. The `value` object is Js::CrossSiteObject<Js::BlockActivationObject>, which fails the assertion.

ISec Lab.
2020.12.16

**Comment by rhuanjl** [comment]
Thanks for the report - this one has been fixed already in master.
