### ISSUE TITLE
Assertion failure in JavascriptOperators::IsUndefinedObject()

### ISSUE THREAD

**Issue by sunlili** [chakra-core/ChakraCore#6540]
Hello, running following code in ch 1.11.24(debug), an assertion will be thrown.
```
var start;
var end;
function opt(buffer) {
    var sc = WScript.LoadScript('', 'samethread');
    buffer += 0;
    var result = buffer.slice(start, end);
    return sc;
}

for (var i = 0; i < 2; i++) {
    var buffer = new ArrayBuffer(8);
    end = opt(buffer);
}
```
output:
```
ASSERTION 25452: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.24\lib\runtime\language\javascriptoperators.cpp, line 10982) !RecyclableObject::Is(instance) ? TRUE : ((RecyclableObject*)instance)->GetScriptContext()->GetLibrary() == library
 Failure: (!RecyclableObject::Is(instance) ? 1 : ((RecyclableObject*)instance)->GetScriptContext()->GetLibrary() == library)
FATAL ERROR: ch.exe failed due to exception code c0000420
```
<img width="873" alt="tmp" src="https://user-images.githubusercontent.com/10752186/102322909-c23a4e00-3fba-11eb-9eeb-bf9c543e36f5.png">

This assertion is triggered in the second time executing `buffer.slice(start, end)`. The `end` is redefined after first calling `opt`, and it becomes a `Js::CrossSiteObject<Js::GlobalObject>`. So when checking in `JavascriptString::EntrySlice()`, the assertion is triggered.

ISec Lab.
2020.12.16

**Comment by rhuanjl** [comment]
Thanks for the report. Whilst this is an issue in 1.11 it has been fixed in master for some time - all the internal type checking logic was re-written to handle subclassing better.
