### ISSUE TITLE
A possible issue about variable redeclaration of ChakraCore.

### ISSUE THREAD

**Issue by ty5491003** [chakra-core/ChakraCore#6546]
###### Version

chakra-1.11.22(release)

###### Test case

```js
if (1) {
    function o() {};
    var o = 1;
}
print(o);
```

###### Execution steps

    ./ChakraCore/out/Release/ch testcase.js

###### Output

```
function o() {}
```

###### Expected behavior

```
throw a SyntaxError about redeclaration of function o
```

###### Description

In above test case, I redeclared `o`, but Chakra neither threw an exception nor redeclared successfully. I think this may be misleading to users, since there is no error, the user will think that the statement was executed successfully.

I've tried other engines, and they all throw `SyntaxError`, So i suspect it's a bug.

Please let me know the result whether this is a bug or not. Looking forward to your reply, thanks! 😆

**Comment by ty5491003** [comment]
BTW, If I remove this `if` statement and redeclare it, it will work. 
```js
function o() {};
var o = 1;
print(o);
```
This case will print `1`.

**Comment by rhuanjl** [comment]
Yes this is a bug, it may be a duplicate of #5076 though I'm not certain.

**Comment by ty5491003** [comment]
Thanks!
