### ISSUE TITLE
Update the copyright text

### ISSUE THREAD

**Issue by rhuanjl** [chakra-core/ChakraCore#6548]
Now the repository is in community control, files need a new copyright banner. We need to retain the existing one BUT should add an extra piece below it about community contribution as any new code will not be written by Microsoft.

Alongside that we probably need a new contributor license agreement.

**Comment by ppenzin** [comment]
What would be the new banner? Note that the current line is not dated, I am not sure if we should add a year to it.

**Comment by rhuanjl** [comment]
Based on the existing license I think we can hopefully put somethign to say:
```
Original work Copyright 2020 (C) Microsoft, all rights reserved.
Modifications made from 2021 Copyright Chakracore Open Source contributors, all rights reserved.
Licensed under the MIT License.
```
And make a similar modification to the License.txt file.

Then we need a contributor license agreement we can possibly borrow the standard microsoft open source one as it's public domain: https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf we'd just have to swap microsoft for whatever we're calling ourselves, possibly Chakracore Open Source team or something? (Unless "Chakracore is a microsoft trademark we need to stop using?)

This is an area I wish microsoft had given us clear instruction on - and perhaps a key question we should ask them - alongside the point on disabling webhooks and access.

**Comment by ppenzin** [comment]
If I remember correctly, unlike license, the banner is not legally binding.

There are quite a few variants of how those are written, different in use of `(c)`, "all rights reserved" and commas. I think many of Github license templates say `Copyright (c) year, author`.

I don't believe ChakraCore is a registered trademark.

A simplification of the above, just a suggestion, I don't feel strongly either way:

```
Copyright (C) 2020 Microsoft, all rights reserved.
Copyright (C) 2021 ChakraCore Contributors, all rights reserved.
Licensed under the MIT License.
```

The downside of having a year in the banner is that we might have to update it annually :)

**Comment by rhuanjl** [comment]
I think we want to make clear that it's work done up to 2020 that is copyright microsoft and anything new that is from public contributors which was the reason for my suggestion.

**Comment by rhuanjl** [comment]
Various pieces of guidance I've seen suggest that modifying (even superficially) the copyright line is problematic/in breach of the license. So I think we may have to just add a line underneath (and not even add a year to the MS copyright.
