### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by rhuanjl** [chakra-core/ChakraCore#6549]
The readme could do with an overhaul to make clear that this project is now owned by the community. And to be clearer on inviting involvement.

All references to microsoft should be moved to a history/background section.

**Comment by ppenzin** [comment]
We also have a mention of "full" Chakra and Edge in repo description.

**Comment by rhuanjl** [comment]
Thinking about the readme one stand out piece is the rolling daily builds, there are also more of these mentioned in the wiki:
https://github.com/chakra-core/ChakraCore/wiki/Build-Status

I think we're going to have bin all of that as they're no way we're keeping it going without quite a few more resources than I imagine the free tier of Azure gives us. Any thoughts should we just delete all those statuses?

Most of the rest of the changes are fairly obvious.

**Comment by ppenzin** [comment]
Deleting seems reasonable - we can always add more statuses as we enable them. It is probably worth documenting what Chakra was doing in the past in case we want to look at it for ideas.
