### ISSUE TITLE
A possible issue with '++' operator apply to 'this' object

### ISSUE THREAD

**Issue by ty5491003** [chakra-core/ChakraCore#6550]
###### Chakra Version

Latest [1.11.24](https://github.com/chakra-core/ChakraCore/releases) Linux(x64)

###### Test case

```js
function func() {
    this++;
}
```

###### Execution steps

    ChakraCoreFiles/bin/ch testcase.js

###### Expected behavior

```
SyntaxError: Invalid left-hand side expression in postfix operation
```

###### Actual behavior

```
(No exception was thrown)
```

###### Description

It is a SyntaxError so it should be thrown whether executed or not.

I've tried other engines, and they all throw SyntaxError, So i suspect it's a bug.

Looking forward to your reply, thanks! 😆

BTW，I also tried it in the Edge browser , which threw a SyntaxError.

**Comment by rhuanjl** [comment]
Thanks for the report - this has been fixed in the master branch of CC and throws correctly:
`SyntaxError: Invalid left-hand side in assignment.`
