### ISSUE TITLE
A possible issue with CC not throwing syntax exceptions correctly

### ISSUE THREAD

**Issue by ty5491003** [chakra-core/ChakraCore#6553]
###### Chakra Version

Latest Commit 9e2f198 (Release Version)

###### Test case

```js
if (1)
```

###### Execution steps

    ./ChakraCore/out/Release/ch testcase.js

###### Expected behavior

```
SyntaxError: Unexpected end of script
```

###### Actual behavior

```
(No exception was thrown)
```

###### Description

Obviously this is a syntax error, however CC does not throw any exceptions. I've tried other engines, and they all throw SyntaxError, So i suspect it's a bug.

**Comment by rhuanjl** [comment]
Hmm comparing with v8, SM and JSC they throw a syntax error for `eval("if(1)")` BUT not for just `if(1)`

CC doesn't throw for either - clearly should throw for the eval case - unsure about the non-eval case.

Should be an easy fix in the parser.

**Comment by rhuanjl** [comment]
This is actually a duplicate of #6351 though that issue speaks of for(;;) and this talks about if() the underlying issue is the same.
