### ISSUE TITLE
An issue about redefining TypeError

### ISSUE THREAD

**Issue by YiWen-y** [chakra-core/ChakraCore#6567]
###### Version

chakra-9e2f198

###### Test case

```js
TypeError.prototype.toString = function() {
    return Error;
};
var a = 1;
a();
```

###### Execution steps

    ./ChakraCore/out/Release/ch testcase.js

###### Output

```

```

###### Expected behavior

```
TypeError: a is not a function
```

###### Description

In the above test case, we redefine `TypeError`, but there is an exception in the redefined function (line 2). When executing the code, since `a` is not a function, `TypeError` will be thrown in line 5. Other engines seem to ignore the exception when redefining `TypeError` (line 2) when executing, and throw a `TypeError` exception normally, but chakra didn't . This seems to be incorrect.

**Comment by ljharb** [comment]
The redefined toString doesn’t have an exception, it would just result in the Error function being stringified, which should never throw. Either way, it appears there’s a bug.

**Comment by rhuanjl** [comment]
Looking at this what happens in CC is:

1. An error is thrown by the `a()` call and the TypeError constructor is evoked
2. The engine is set into exception state
3. `ch` (the command line host) clears the exception and gets the error object
4. `ch` attempts to convert the error object into a string (this invokes the overwritten toString method) but returns the Error constructor object not a string
5. `ch` attempts to display the returned object - but it doesn't have a display string and so it displays a blank message
6. `ch` exits (if you include additional code after `a()` it will not be run)

If this is an error it would be an error in `ch` not chakracore itself (unless overwritting `NativeError.prototype.toString` is meant to be forbidden?) - though I'm not sure what would you expect it to do exactly? (if your overwritten toString returns a string it will be displayed)

@ljharb be interested what you think

**Comment by ljharb** [comment]
@rhuanjl the spec requires that the output to toString be ran through the ToString abstract operation, so the Error constructor should become `’[object Error]’`, i believe. So the error is between steps 4 and 5.

**Comment by rhuanjl** [comment]
> @rhuanjl the spec requires that the output to toString be ran through the ToString abstract operation, so the Error constructor should become `’[object Error]’`, i believe. So the error is between steps 4 and 5.

@ljharb thanks for the comments, looking at it more - I missed a step actually, please could you take another look and tell me if this actual behaviour is right?

Looking at 4 from above we go to:
a) ToString - this calls ToString(ToPrimitive)
b) ToPrimitive in turn calls OrdinaryToPrimitive
c) OrdinaryToPrimitive does
    i) result = TypeError.prototype.toString
    ii) if Type(result) != object, return result // Type is object so next step
    iii) result = TypeError.prototype.valueOf(result)
    iv) if Type(result) != object, return result // type still is object so next step
    v) throw new TypeError

As we got here from attempting string conversion from an error in the host there is no handler for this new error and the engine just exits.

However if we do this:
```js
TypeError.prototype.toString = function ( ) {print("hi"); return Error;}

try {
print(new TypeError());
} catch (e)
{
  print("caught");
  print(e.message);
}
```

We get the `caught` leg and display the new error message that a string was expected (note that if we do print(e) it will throw the same exception and not print).

**Comment by ljharb** [comment]
@rhuanjl actually I'm not sure the spec governs this. What the host does when it gets an uncaught error is entirely implementation-dependent - `throw { toString() { return Error } }` in a browser or node gives me `console.log()` of that object, and in an uncaught exception handler i expect it would give me the same thing.

In other words, ch here has *chosen* to not display something reasonable in this case, and I think it's entirely within your purview to change that choice (and it's probably best to match what node and browsers do).

**Comment by rhuanjl** [comment]
So my conclusion is chakracore functions correctly on this but `ch`'s behaviour is unhelpful We could update `ch` to output something here which may make testing some fringe issues easier.

**Comment by rhuanjl** [comment]
I may come back to this or it's fairly easy issue for someone else to work on - you'd need to look here:
https://github.com/chakra-core/ChakraCore/blob/3bbeede3077c316c04c70a63713584faa584072e/bin/ch/WScriptJsrt.cpp#L1786

That call will attempt to coerce the error to a string and error out triggering the IfJsrtErrorFail flag - you need to edit this to catch the error and print an alternative message - be careful that you're already in the PrintException function - don't want to do anything that could create an infinite loop. Perhaps output a specific message saying error string coercion failed or try getting the "message" property of the error instead or something.

**Comment by ljharb** [comment]
Personally I'd expect printing an object would display a useful display of the object, like `console.log` or https://npmjs.com/object-inspect does.

**Comment by rhuanjl** [comment]
Found a relatively easy fix to display the original error. Note could not simply walk the object because the error object would be:
```js
{
  message : "a is not a function",
  get stack() { /* a function that calls this.toString() and hence throws */}
}
```
Wanted to display more than just the message hence used an alternate CC API to get at the information.

**Comment by YiWen-y** [comment]
###### Test case

```js
Object. defineProperty(Object. prototype, Symbol. toPrimitive,{
    get: function(){
        print(' get');
        throw Error();
    }
}); 
print(1); 
a(); 
print(2);
```

###### Output

```
1
get
```

###### Expected behavior

```
1
get
ReferenceError: a is not defined
    at testcase.js:8:1
```
During the execution of this test case, I observed a similar phenomenon (when the fourth line of code was commented out, the execution result was normal). I guessed that these two cases were triggered by the same reason, right?

**Comment by rhuanjl** [comment]
Yes this is the same issue. With the change in #6581 
Your new test case will output:
```
1
 get
ERROR attempting to coerce error to string, using alternate handler
'a' is not defined
        at code (testcase.js:95:1)
```

And for comparison v8 does:
```
1
 get
/var/folders/1v/7ntmwhfs5799zh90q04c9vr80000gn/T/121027-13873-ph0lw5.tgekf.js:95: <string conversion failed>
a(); 
^
ReferenceError: a is not defined
    at /var/folders/1v/7ntmwhfs5799zh90q04c9vr80000gn/T/121027-13873-ph0lw5.tgekf.js:95:1
```

**Comment by YiWen-y** [comment]
I understand. Thanks for your reply.
