### ISSUE TITLE
[Community] GSoC

### ISSUE THREAD

**Issue by ppenzin** [chakra-core/ChakraCore#6579]
Google Summer Of Code will start accepting applications soon. As we are (now) an independent organization, we can throw our name in the hat. I believe the minimum requirements are having two mentors.

Timeline: https://developers.google.com/open-source/gsoc/timeline

**Comment by rhuanjl** [comment]
It's an interesting idea - getting a couple of "interns" to write some extensive code for us would be great - also the grant google gives could fund some better CI stuff or the like.

The requirements do say the organisation needs to have released an open source product AND have 2 mentors - so to qualify we may need to have done a community release before we apply.

**Comment by ppenzin** [comment]
Application submitted. We probably need to populate the project ideas wiki page: https://github.com/chakra-core/ChakraCore/wiki/Project-Ideas

**Comment by rhuanjl** [comment]
Added a few project ideas.
