### ISSUE TITLE
Document or delete BUILD.gn

### ISSUE THREAD

**Issue by rhuanjl** [chakra-core/ChakraCore#6584]
`BUILD.gn` in the project root is a build script for use with the GN build system, see: https://gn.googlesource.com/gn/+/master/docs/quick_start.md

It redirects to `tools/run_msbuild.py` which only works on windows.

I've never heard of the GN build system before is there any clear benefit of having a script for it, particularly a windows only one? If yes should mention it in the building section of our readme if no should delete both these files.

Opinions?

**Comment by Penguinwizzard** [comment]
The GN build system is what's used in Chromium (and thus the new Edge). It's actually pretty fantastic, and would be worth considering moving the project to if it weren't relatively niche. Coming from working on Chakra to Edge, it's way better than most other build systems I've worked with, although admittedly the benefits become more apparent with larger projects.

**Comment by ppenzin** [comment]
@Penguinwizzard do you know if there is a way to build ChakraCore via a public chromium-related project?

**Comment by Penguinwizzard** [comment]
I do not believe there is currently any such project that _intrinsically_ supports this; you can probably get gn via the chromium depot_tools repository's tooling, and then point it at the BUILD.gn here, but it wouldn't be a terribly useful exercise.

**Comment by rhuanjl** [comment]
GN is available for public download from here: https://gn.googlesource.com/gn/ and a bit of googling shows that some other people are using it not just chromium but not many.

Its public usage is fairly new and I think it's highly unlikely that many people will be seeking to integrate CC into a larger GN managed project - or would benefit from the script we have here when doing so - particularly as the Gn file we have simply invokes a python script to call msbuild.

**Comment by ppenzin** [comment]
I think GN is still a bit niche (as is Bazel, to be totally honest), though it has advantages, but we are not benefiting from them it if we are only calling msbuild.
