### ISSUE TITLE
The prototype chain does not match the object

### ISSUE THREAD

**Issue by YiWen-y** [chakra-core/ChakraCore#6589]
###### Version

chakra-1.11.24

###### Execution step

    ./ChakraCore/out/Release/ch testcase.js

###### Test case 1

```js
var s = new String('abcd');
print(typeof s);
print(s);
s.__proto__ = Function.prototype;
print(s);
```

###### Output 1

```
object
abcd
abcd
```

###### Expected behavior 1

```
object
abcd
at testcase.js:5:1 TypeError: Function.prototype.toString called on incompatible object
```

###### Test case 2

```js
var s = new String('abcd');
print(typeof s);
print(s);
s.__proto__ = Object.prototype;
print(s);
```

###### Output 2

```
object
abcd
abcd
```

###### Expected behavior 2

```
object
abcd
[object String]
```

###### Description

When executing the above test case, the prototype chain of the modified object `s` was modified in the line 4. The output of chakra is inconsistent with other engines (spidermonkey, v8, JavascriptCore, etc.). It seems that the implementation of chakra is incorrect.

**Comment by ljharb** [comment]
Technically there’s no spec for `print` here.

Personally i find either of the third outputs to be less useful - it should print out something that reveals that it’s a boxed String object, that has its prototype set to Object.prototype and not String.prototype (node’s util.inspect has helpful output here) but it’s entirely up to chakra if it chooses to do this.

**Comment by rhuanjl** [comment]
Our print implementation is in `ch` which is intended as a testing/demonstration tool. So unless a change is needed for demonstrating a feature OR enabling use with some other tooling (such as test262) it's somewhat low priority.

That said for reference what it's doing in pseudo code is:

```js
function print(...inputs)
{
  for (const input of inputs)
  {
    if (input is not a string) // detected by checking the internal data in C++
    {
      input = input.toString();
    }
    display(input);
  }
}
```

So in the examples above toString() is not being called as it sees it's already a string.

For more intricate test cases I often define a simple helper `function printout(x) {print(JSON.stringify(x))};`
