### ISSUE TITLE
Exposing new features by replacing chakra.dll with a ChakraCore build ?

### ISSUE THREAD

**Issue by ShortDevelopment** [chakra-core/ChakraCore#6616]
I've got a special question:
Is it possible to build ChakraCore and replace chakra.dll on Windows to expose new features to PWA (and Edge Legacy)?
I've read there are only a fiew differences between Chakra and ChakraCore?
If it is: How could it be done?

**Comment by rhuanjl** [comment]
Certainly not with Edge. I don't know what PWA is.

To clarify on the difference between Chakra and ChakraCore:

**ChakraCore is an open source javascript engine** - previously developed and maintained by microsoft, now maintained by a small group of open source contributors.

**Chakra was a closed source MS product** it used to be built by taking ChakraCore and:
- removing (via #ifdef) new/experimental APIs
- adding (via #ifdef) various hooks for tying in directly with Edge and other windows Apps
- adding additional private code (not in this repository and never open sourced) to do with connecting to the Windows runtime

I think the last version of Chakra was linked to ChakraCore 1.11. In theory a newer version of ChakraCore from our master branch could be built into Chakra with the right build flags BUT you'd need the additional private code or it's not going to run - as Microsoft never open sourced that I doubt you could get hold of it.

**Comment by ShortDevelopment** [comment]
Well, thank you fore you quick response!
With PWA (Progressive Web Apps) I meant the js and EdgeHTML powered apps from Windows Store.
It's sad to hear that this will likely never be possible…

**Comment by rhuanjl** [comment]
I suppose we could ask MS if they'd be willing to publish the private components of Chakra - I'd be surprised if they did AND they definitely wouldn't support it.

**Comment by ShortDevelopment** [comment]
I think it would be worth a try!
It seems that MS is throwing away Edge Legacy completely and in my opinion it’s only a matter of time until they also replace EdgeHTML in PWAs completely with WebView2 (Chromium).
So this code wouldn’t have any use in not so fare future!

**Comment by ShortDevelopment** [comment]
> * adding (via #ifdef) various hooks for tying in directly with Edge and other windows Apps    

Do you know which constants lead to an activation of those else necessary components?

**Comment by rhuanjl** [comment]
> > * adding (via #ifdef) various hooks for tying in directly with Edge and other windows Apps
> 
> Do you know which constants lead to an activation of those else necessary components?

Anything behind NTBUILD including some stuff I deleted in these commits:
https://github.com/chakra-core/ChakraCore/commit/d1ae883b04bd1701f775e66414fb32f70a0a6f9b
https://github.com/chakra-core/ChakraCore/commit/befa2b30b8526ca0f36a63c3e229f965235db8d1
https://github.com/chakra-core/ChakraCore/commit/34092e04f74943fce0b1e033c75dceef4c3a858f

BUT it's useless without the private MS code and whilst we can ask, I think the odds of MS giving that out are quite low

**Comment by ppenzin** [comment]
CC @LouisLaf and @digitalinfinity

**Comment by pleath** [comment]
AFAIK, there has never been any movement toward open-sourcing chakra.dll, and I don't expect there to be any at this point. The way forward for MSFT to support new JS features will most likely be V8.

**Comment by LouisLaf** [comment]
The biggest difference between Chakra.dll and ChakraCore.dll is that we removed the API between Chakra.dll and the rest of the browser (relics from IE days), because we wanted the ChakraCore JS API to be the public way to interface with Chakra. So there is no way to get ChakraCore.dll and EdgeHTML to work together...

**Comment by ShortDevelopment** [comment]
Well, that’s what I „feared“.
Using API Monitor, I saw that practically every public API function (from chakra.dll) that was not starting with JS wasn’t available in a recent ChakraCore build…

**Comment by rhuanjl** [comment]
> Well, that’s what I „feared“.
> Using API Monitor, I saw that practically every public API function (from chakra.dll) that was not starting with JS wasn’t available in a recent ChakraCore build…

The bulk of the underlying logic is there, but the build config is different and as mentioned there are private components we don't have. Without microsoft deciding to publish/open source the remainder of chakra this is a dead end - and it sounds like the answer is a "probably not" to that question.

**Comment by lukemcdo** [comment]
Is this question asking specifically about trying to use ChakraCore in Legacy Edge? Or is it just in the interest of running ChakraCore in a web browser in general?

**Comment by ShortDevelopment** [comment]
In first place, it's about giving EdgeHTML new features in sence of JS.
But the second proposed question would olso be very interesting: Is the remaining Api powerful and performant enough to power a modern web browser? (except the missing new JS specifications (es...))

**Comment by lukemcdo** [comment]
Well, EdgeHTML isn't going anywhere from what we know. It'd be interesting to see how much work would be needed to drop ChakraCore in to replace KJS in KHTML (yes, old, but open and provably can be extended into a modern browser).

**Comment by curtisman** [comment]
> But the second proposed question would olso be very interesting: Is the remaining Api powerful and performant enough to power a modern web browser? (except the missing new JS specifications (es...))

ChakraCore should have most of what you need to run with modern browser.  I did a quick hacky prototype that shim's v8 API (similar to the shim that enables node-chakra) and able to run Chromium with pretty good perf.  Most of the additional code to wire up with any HTML engines deals with projecting the DOM into the JS context and memory management between the two sides.

**Comment by rhuanjl** [comment]
> Well, EdgeHTML isn't going anywhere from what we know. It'd be interesting to see how much work would be needed to drop ChakraCore in to replace KJS in KHTML (yes, old, but open and provably can be extended into a modern browser).

I'd love to see a project like this go ahead, I wouldn't have the time to contribute much (if at all) but would be happy to advise on how to work with the CC API as needed.

**Comment by ppenzin** [comment]
I would be very interested in this project, at the very least because it exposes the engine to more important JS use cases.

@curtisman would you be able to share your solution? Also, were there any attempts like this with WebKit?

**Comment by digitalinfinity** [comment]
While I'm not sure about @curtisman's project, we had a publicly available shim for v8 on top of ChakraCore that we used in the node-chakracore project- that is probably a reasonable starting point if anyone wanted to plug ChakraCore into a browser: https://github.com/nodejs/node-chakracore/tree/master/deps/chakrashim

**Comment by rhuanjl** [comment]
> While I'm not sure about @curtisman's project, we had a publicly available shim for v8 on top of ChakraCore that we used in the node-chakracore project- that is probably a reasonable starting point if anyone wanted to plug ChakraCore into a browser: https://github.com/nodejs/node-chakracore/tree/master/deps/chakrashim

I actually spent a while trying to add ESModule support to that shim a while ago, not sure if I new enough about what I was doing at the time.

I agree that starting from there would almost certainly be the quickest way to get some kind of browser running with chakracore - though it would be far "prettier" (and far far more work) to do it without shimming v8's api on top.
