### ISSUE TITLE
Supported ECMAScript Spec.

### ISSUE THREAD

**Issue by qiudaoyuyesok** [chakra-core/ChakraCore#6617]
Please tell me the ECMAScript Spec. which the latest version of ChakraCore (v1.11.24) supported.

**Comment by MadProbe** [comment]
You can view supported proposals list here - https://github.com/chakra-core/org/blob/master/tc39%20Proposals.md

**Comment by rhuanjl** [comment]
It has 99% of ES6 (everything but a few bugs + regexp unicode mode is incomplete) then all the features marked "In 1.11" at the link @MadProbe gave.

All the features marked "In Master" at that link should be included in version 1.12 - which we will hopefully be able to release by the summer...
