### ISSUE TITLE
Overlap button with stickly navbar

### ISSUE THREAD

**Issue by mingbackmountain** [chakra-core/ChakraCore#6713]
<img width="1440" alt="Screen Shot 2564-05-02 at 20 33 15" src="https://user-images.githubusercontent.com/25886138/116815018-d061c300-ab85-11eb-8dec-2e7014eb016c.png">
 
Hi, guys, I'm trying to achieve stickly navbar. However, I just found that the button component seem to overlap when I the stick properties

`  <Flex
            as="nav"
            align="center"
            justify="space-between"
            wrap="wrap"
            w="100%"
            pt={6}
            pb={6}
            pr={24}
            pl={24}
            bg={"white"}
            boxShadow="md"
            position="sticky"
            top="0"
            >`

Here is my setup for my navbar 

Can some body help me with this issue?

**Comment by rhuanjl** [comment]
I'm sorry I think you've found the wrong repository for this, this is not to do with chakra-core. You probably want an html help page/html community of some kind.
