### ISSUE TITLE
[JSRT API] Issue about JsIsCallable

### ISSUE THREAD

**Issue by MadProbe** [chakra-core/ChakraCore#6720]
`JsIsCallable` returns true if a class expression is passed - Was it intended to return true?

**Comment by MadProbe** [comment]
Sorry, that was a bug in my code )

**Comment by rhuanjl** [comment]
Interesting - that may be a bug, the actual implementation is on line 38 of JavascriptConversion.cpp with the method: `bool JavascriptConversion::IsCallable`

I think the issue may be that the way classes are implemented they technically are callable they just throw when called.

**Comment by MadProbe** [comment]
Should i fix this or will we keep this behaviour?

**Comment by rhuanjl** [comment]
It's a master only api at the moment - so IMO safe to change.

BUT not sure what else may use bool JavascriptConversion::IsCallable, so safer/simpler change would be just to edit the API to check an extra condition here:
https://github.com/chakra-core/ChakraCore/blob/153892e08c16b3a9658e30ba5ff65b1cf2224572/lib/Jsrt/Core/JsrtCore.cpp#L1459-L1465
