### ISSUE TITLE
How to get REMOTE_ADDR in code.js?

### ISSUE THREAD

**Issue by Arkady23** [chakra-core/ChakraCore#6728]
How to get the environment data in the code.js? For example, REMOTE_ADDR, QUERY_STRING, HTTP_COOKIE, and others. Is it possible to do this regardless of the Windows or Linux operating system?

**Comment by MadProbe** [comment]
I don't understand but how is this related to CC?
If you want to post such a question issue, please do it in the code.js repository (or how is it named? - idk) and only if "code.js" means a framework.
If code.js means a file, ch.exe doesn't provide such functionality, or if you embed CC, make this yourself by the available JSRT API.

**Comment by Arkady23** [comment]
Client browser address bar:
`http://192.168.1.123/cgi-bin/code.js`

Server Windows code.js:
```
#!C:/CC/ch.exe
print("Content-Type: text/html\r\n\r\n");
...
```
Or server Linux  code.js:
```
#!/bin/ch
print("Content-Type: text/html\r\n\r\n");
...
```
This only works on Windows:
```
#!C:/Windows/SysWOW64/cscript.exe //Nologo
<job>
<script>
  WScript.StdOut.Write("Content-Type: text/html\r\n\r\n");
  Wsh = new ActiveXObject("WScript.Shell");
  WScript.StdOut.Write(Wsh.ExpandEnvironmentStrings("%REMOTE_ADDR%"));
</script>
</job>
```

**Comment by MadProbe** [comment]
ch(.exe) doesn't provide such functionality, as i've said earlier.
I can advise you only making a program which works with the JSRT API and by it you create a function, which acts in similar fashion as the `Wsh.ExpandEnvironmentStrings` you've illustrated.
JSRT API manipulation examples:
* this repo - /bin/ch/WScriptJsrt.cpp (language: C++)
* https://github.com/fatcerberus/sphere (language: C)
* https://github.com/MadProbe/PythonChakra (language: Python)

**Comment by Arkady23** [comment]
Thanks :(
This is unnecessarily difficult. I found a simple way using node:
```
#!D:/Install/nodejs.org/node/node.exe
  console.log("Content-Type: text/html\r\n\r\n");
  console.log(process.env.REMOTE_ADDR);
```

**Comment by rhuanjl** [comment]
ch(.exe) is a very limited app meant for testing chakracore, whilst you're welcome to use it, it has very limited functionality.

As MadProbe has said above the intent of using chakracore for serious purposes is to make your own application that links to it.
