### ISSUE TITLE
How to run an external program in the code.js?

### ISSUE THREAD

**Issue by Arkady23** [chakra-core/ChakraCore#6729]
How to run an external program in the code.js? For example, SQLite. Is it possible to do this regardless of the Windows or Linux operating system?

**Comment by rhuanjl** [comment]
Assuming you're embedding chakracore in programme you're developing you will need to setup the integration with the external programme then create a JavaScript function that involves it via a callback.

I can give you the steps for the JS invocation (let me know if you want this) but you'll need your own setup on the native side.

**Comment by Arkady23** [comment]
Thanks. I decided to use node.js from Google.
