### ISSUE TITLE
Wrong documentation comment

### ISSUE THREAD

**Issue by pollnossa** [chakra-core/ChakraCore#6730]
Hi everyone.

Here is small issue in opcodes comment-documentation
https://github.com/chakra-core/ChakraCore/blob/master/lib/Runtime/ByteCode/OpCodes.h#L165
Comment shoul be the following - // Branch if object has the given property ...
The same is for BrOnHasEnvProperty.

Thank you.

**Comment by rhuanjl** [comment]
Thanks for the note, you're correct those comments are wrong
