### ISSUE TITLE
Build.sh may be broken on latest Ubuntu

### ISSUE THREAD

**Issue by rhuanjl** [chakra-core/ChakraCore#6731]
Whilst it is now possible to build directly with cmake and skip the build.sh script altogether whilst we continue to provide it we should keep it functional...

New versions of Ubuntu ship without Python2.

Build.sh reference to Python2 for optional LLTng support; AND for setting a relative path and this can cause a build failure on Ubuntu 20 - as per @fatcerberus

We should update build.sh to try checking for python 3 if python 2 is not found.

**Comment by rhuanjl** [comment]
@ppenzin there's also an apparent point that unless you supply a flag to specify Clang, CMake defaults to the system compiler (which on some flavours of linux is gcc) BUT the build fails if you don't use Clang.

So.... building within CMake directly is still slightly awkward AND build.sh is broken on the latest Ubuntu.... ugh.

**Comment by rhuanjl** [comment]
Possible fix to skip the python2 invocation when LTTng is not enabled: https://github.com/chakra-core/ChakraCore/commit/14d8edbfa29dd8f75ded04539ad725dcc9344050

**Comment by ppenzin** [comment]
We can reopen if we want to continue working on this, though there is another issue about GCC support (below).

> CMake defaults to the system compiler (which on some flavours of linux is gcc) BUT the build fails if you don't use Clang.

GCC is default compiler on all major Linux distros. We have a draft PR by @curtisman for enabling partial GCC support, #6611. Also there is more background on this issue in #2038.

I think we can also add a build to CI that would use build.sh if that is worth it.
