### ISSUE TITLE
Discord invitation in readme is invalid

### ISSUE THREAD

**Issue by Pospelove** [chakra-core/ChakraCore#6734]
> ![image](https://user-images.githubusercontent.com/37947786/126847640-da9ccf2c-6edc-4179-ac96-d9a50170a346.png)

**Comment by rhuanjl** [comment]
Here is an updated invite: https://discord.gg/dgRawPdNuC Will update the readme later

**Comment by rhuanjl** [comment]
#6735 opened to fix the readme

**Comment by Pospelove** [comment]
Thanks!
