### ISSUE TITLE
chakra require () after catch

### ISSUE THREAD

**Issue by YiWen-y** [chakra-core/ChakraCore#6807]
###### Version

```
chakra-1.11.24.0
```

###### Test case

```js
var foo = function () {
    try {
        print("1")
    } catch {
    }
};
foo();
```

###### Execution steps 

    /root/.jsvu/ch Testcase.js

###### Output

```
SyntaxError: Expected '(' at code (javascriptTestcase_eut5pcps.js:4:12)
```

###### Expected behavior

```
1
```

###### Description

When executing this test case, other engines can execute normally and output the expected result `1`, but chakra throws a syntax error in line 4. It seems like chakra requires `()` after `catch`, or it won't work properly.

**Comment by AidPaike** [comment]
This bug has been silently fixed in the latest version of [ChakraCore](https://github.com/chakra-core/ChakraCore).
