### ISSUE TITLE
  Add native support for AssemblyScript

### ISSUE THREAD

**Issue by jayadevanraja** [chakra-core/ChakraCore#6818]
This issue is with reference to another issue from 6 years ago:
https://github.com/chakra-core/ChakraCore/issues/1435

Will supporting AssemblyScript be a good idea? This is not a proposal, but I was wondering if any knowledgable person could enlighten me (and others) about the pros and cons of supporting native AssemblyScript in the browser.

**Comment by ljharb** [comment]
In what browser?

**Comment by MaxGraey** [comment]
Built-in support for interpreted langs like Dart, Python, or TypeScript might still make some sense, but AssemblyScript produces WebAssembly binaries, so only WebAssembly support would be sufficient.

**Comment by jayadevanraja** [comment]
@ljharb In any browser, generally. I think that this can speed-up the whole web. Yes, there are political hurdles. But I am thinking that technical hurdles are almost non-existent, since these enhancements in the type system can be considered to be JavaScript with static types.

@MaxGraey Assemblyscript has text and binary format. V8 or SpiderMonkey can interpret and compile and even perform JIT on Javascript. That compilation will be made much easier when programmer or library has already specified types. That is my understanding. Please correct me if I am wrong.

**Comment by ljharb** [comment]
@jayadevanraja you'd need to convince the *browsers* (and likely the HTML spec authors) to do that, and since chakracore isn't in any browsers, this repo wouldn't affect it.

**Comment by jayadevanraja** [comment]
@ljharb Can I read your opinion as "The hurdles are only political, and not technical"?

**Comment by ljharb** [comment]
@jayadevanraja my personal opinion is that it's a terrible idea for technical, ux, and political reasons, but it's not up to me. Either way, it's irrelevant *for this repo* because chakracore isn't part of the web.

**Comment by jayadevanraja** [comment]
Thanks. If this is irrelevant, I shall close the issue.
