### ISSUE TITLE
Deprecation of `Ubuntu 18.04` Actions (DevOps)

### ISSUE THREAD

**Issue by ShortDevelopment** [chakra-core/ChakraCore#6855]
Ubuntu18 tests will already fail during scheduled `brownout`.
They will be fully unsupported by 4/1/2023.

See https://github.com/actions/runner-images/issues/6002, #6831.
PR: https://github.com/chakra-core/ChakraCore/pull/6833

**Comment by rhuanjl** [comment]
Currently CC fails to build on Ubuntu 22, we're intending to drop Ubuntu 18 jobs when the Ubuntu 22 build works - hopefully soon...

**Comment by ppenzin** [comment]
Failure is with only one build (Release with debug info, AKA test), we can keep that one on Ubuntu 20 if we need to move off Ubuntu 18 asap.

**Comment by ShortDevelopment** [comment]
Fixed by #6958
