### ISSUE TITLE
Debugging ChakraCore : Boolean valueOf

### ISSUE THREAD

**Issue by bkimman** [chakra-core/ChakraCore#6864]
I am using Visual Studio 2015.

When I try to debug my application, it does not step into the Chakra code - I have built the Chakra solution on the same machine and the Debug Output window indicates that the symbols for ChakraCore.dll have been loaded.

If I locate the source file in chakra where a particular function is, and put a break point there, the debugger does stop there and lets me debug the code .. different matter that debugging c++ is not easy for me.

I had to debug in the context of an issue .. a script was passing a native function a boolean object where a boolean value was expected. The native function determined that that argument was an instance of the Boolean object and so tried to convert that to the boolean value ..

Tried with ConvertValueToBoolean - that always returns a value of false.
Tried calling the valueOf function of the Boolean object - that returns an object and not a value.
But ConvertValueToString returns the correct value.

Thanks
K

**Comment by rhuanjl** [comment]
Two separate topics:

1. If you're looking to do step through debugging of Javascript with chakraCore you would need to implement your own debugger - ChakraCore provides a debugging API see lib/Jsrt/ChakraDebug.h for the APIs
2. The use of the APIs you mentioned, as far as I know these all work correctly, if you're getting unexpected behaviour please can you share a code snippet and I'll take a look

**Comment by bkimman** [comment]
Thanks for the reply.

On 1 .. I was actually trying to debug the chakra code itself and not the javascript. With Studio 2015 it does not step into the chakra code for some reason. I have to figure where in jsrt.cpp it will reach and put a breakpoint there. No idea why this happens.

On 2 .. It does work correctly. JsConvertToBoolean reaches JavascriptConversion::ToBoolean_Full .. here as per the es spec, if the input value is an Object, it will return true. So even though the value being passed is one created by **New Boolean(false)**, since it is an object, as per the spec to ToBoolean will return true. 

So for this one has to call the valueOf function on the prototype of Boolean to determine the actual value.

Thanks again.

K

**Comment by rhuanjl** [comment]
Interesting, on point 1 I can step into Chakracore code with lldb, not sure what the issue you're having is, could it be that you're trying to activate debugging too late?
