### ISSUE TITLE
ChakraCore : Dynamic Module Import

### ISSUE THREAD

**Issue by bkimman** [chakra-core/ChakraCore#6870]
As part of building C samples for chakra, am now working on modules.

For this I am using the examples posted by Mozilla at
https://github.com/mdn/js-examples/tree/main/module-examples

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules is the place where they explain the examples.

All the examples have a canvas module which in turn uses square, circle and triangle modules to draw the different shapes, reporting their actions in an Unordered List.

I created a pseudo DOM in a js script which I parsed in the console application before parsing the main module.

The first module is parsed with JsModuleParse.

In the FetchImportedModuleCallback callback, I queued other imported modules for parsing.

The parsing continues till there are no more modules to parse - this results in a call to NotifyModuleReadyCallback on the root module.

I am then calling JsModuleEvaluation.

With this sequence, all the examples, except for one, were working fine.

The one which is different uses dynamic module import like this...

```
let squareBtn = document.querySelector('.square');
squareBtn.addEventListener('click', () => {
  import('./modules/square.js').then((Module) => {
    let square1 = new Module.Square(myCanvas.ctx, myCanvas.listId, 50, 50, 100, 'blue');
    square1.draw();
    square1.reportArea();
    square1.reportPerimeter();
  })
});
```

I have managed to get it to work as follows:

The main module and the canvas module are parsed first; and the main module is evaluated. This is the same as the sequence for the other examples.

Then I call the 'click' function on the button to trigger the dynamic import. 

When this function is invoked, the following is the sequence:

a) callback is received in FetchImportedModuleCallback for the dynamically imported module.
b) in the callback I invoked JsModuleParse
c) the callback NotifyModuleReadyCallback was received
d) in this callback I invoked JsModuleEvaluate and then JsGetModuleNamespace

But the result of the click did not show up. 

Since this is a dynamic import which returns a Promise, I set a PromiseContinuationCallback callback before calling the 'click' function.

When the module is evaluated, the PromiseContinuationCallback callback is invoked twice .. in both cases the 'task' parameter is a JsFunction. A call to toString on this function indicates it is a native function.

While calling the function I passed a single argument of the module's namespace. With this, the result of the click showed up just right. bingo!

When I passed no arguments to the function, or 'undefined' as the argument, the results of the click were incomplete but no exception was raised.

Questions:

a) What is the argument that should be passed to the 'task' function - in my simple program, I knew the promise was triggered by the import and so I passed the module's namespace; but in a more complex example this would not be the case - so how does one determine what the argument should be? 

The JsSetPromiseContinuationCallback provides a callbackState parameter but if I call this in the NotifyModuleReadyCallback, will it not overwrite a previously set callbackState value?

b) When is the FetchImportedModuleFromScriptCallback callback made? Looking at the name, I thought it would be used for dynamic imports, but the callback made for dynamic imports was still FetchImportedModuleCallback.

c) In FetchImportedModuleCallback for the dynamic module, I created a new ModuleRecord and called JsModuleParse .. when this function returned, I returned the new module record in the out parameter JsModuleRecord* dependentModuleRecord.  This did not cause any problem - is this the way the dynamic import should be handled?

Thanks

Kimman

**Comment by rhuanjl** [comment]
I'm a little rusty but I think I remember all of this...

**a) the "task" function** from the PromiseContinuationCallback is a pointer to the internal `ResolveThenableTaskFunction` for the relevant promise, I believe it ignores its parameters (it has a baked in internal slot holding the promise it's going to resolve). The reason it is called twice in your example is that the first call is resolving the promise from the `import()` and the second is resolving the promise from the `.then()` in your example.

The `callbackState` parameter is simply handed back and forth, CC does nothing with it. It is intended to hold any information your host needs when handling a PromiseContinuationCallback - The expected use of this is for a pointer to a queue of promise resolutions for you to resolve one at a time. In a spec conformant host you're not meant to start resolving one promise resolution until the last one has finished - calling the first TaskFunction may result in the second call of the PromiseContinuationCallback - and you're meant to record the task it provides but not call it yet but rather wait until the first TaskFuntion call returns before you call it, hence needing a queue of some kind.

**b)** FetchImportedModuleFromScriptCallback is used when `import()` is called from a script, NOT a module. If all your JS files are modules then it is never used. The key difference is it doesn't have a "referencing module" so may have to use a different specifier/path resolution algorithm.

**c)** FetchImportedModuleCallback should implement the following steps for both `import` and `import()`:
1. check if the requested module already has a module record, if yes return it (done)
2. if it does not already have a module record, create a module record for it
3. if a module record has been created schedule a call to JsParseModuleSource for this record, this be done from your event loop or equivalent (some kind of queue mechanism processed after the callback returns), not immediately (it can generate further calls to FetchImportedModuleCallback and so the processing order can go wrong if it is called within he callback - additionally if there are circular imports A imports B and B imports A you could end up with infinite recursion)

**Comment by rhuanjl** [comment]
Also, if you wish to support Top Level Await, you should also implement a `reportModuleCompletionCallback`

**Comment by bkimman** [comment]
Thanks very much

**Comment by bkimman** [comment]
> if a module record has been created schedule a call to JsParseModuleSource for this record, this be done from your event loop or > equivalent (some kind of queue mechanism processed after the callback returns),

This part seems a little difficult in the context of dynamic import.

In the examples from MDN, the import() is invoked in a onclick function. So I used JsCallFunction to run that function .. the FetchImportedModuleCallback  is made at this point .. if I were to wait to queue the parsing of the module after JsCallFunction returns, it would not make much sense would it?

K

**Comment by rhuanjl** [comment]
> > if a module record has been created schedule a call to JsParseModuleSource for this record, this be done from your event loop or > equivalent (some kind of queue mechanism processed after the callback returns),
> 
> This part seems a little difficult in the context of dynamic import.
> 
> In the examples from MDN, the import() is invoked in a onclick function. So I used JsCallFunction to run that function .. the FetchImportedModuleCallback is made at this point .. if I were to wait to queue the parsing of the module after JsCallFunction returns, it would not make much sense would it?
> 
> K

It is meant to wait - dynamic import is meant to be Async so in this example:

```js
function onClick() {
  import('boo').then(()=>{console.log('boo imported'));
  console.log('on Click finished');
}
```

A spec compliant implementation would log 'on Click finished" before logging "boo imported".

**Comment by bkimman** [comment]
Thanks Richard for pointing out my basic understanding gap.

Now your suggestion on the implementation makes sense .. and makes it cleaner than I had thought it would be.

K
