### ISSUE TITLE
Native Functions and Uncaught Exceptions

### ISSUE THREAD

**Issue by bkimman** [chakra-core/ChakraCore#6873]
I have enabled debugging in the runtime and provided a callback for debug events.

I also called JsDiagSetBreakOnException(runtime, JsDiagBreakOnExceptionAttributeUncaught);

If there is an exception in the script which is not caught, the debug event callback is provided and I am able to get all the diagnostic information.

However, if I call a native function from the script and in that function I create an exception and call JsSetException; the debug event callback is not made.

Stepping through the chakra code, I noticed that in 

JavascriptExternalFunction.cpp Line 320
JavascriptExceptionObject* recordedException = scriptContext->GetAndClearRecordedException(&considerPassingToDebugger);

The considerPassingToDebugger is set to false .. if I force it to true the debug event callback is provided with all the diagnostic information.

I tried another 'trick' .. I compiled a js function to just throw an error .. and from my native function I called that function instead of calling JsSetException - but even then the debug event callback is not made.

Is this by design that exceptions from native functions will not get routed to the debugging callback?

K

**Comment by rhuanjl** [comment]
@fatcerberus were you able to work with/around this with SSj?

@bkimman I'm afraid I've never worked on the debugger code in CC and no one who did is still involved in the project - I could try and work through why errors from native methods are not sent to the debugger but may take a bit of time.

**Comment by rhuanjl** [comment]
(My previous answer was incorrect)

There is a runtime attribute: JsRuntimeAttributeDispatchSetExceptionsToDebugger which can be set when calling JsCreateRuntime, I think this will enable debugger interrupts for native exceptions.

**Comment by bkimman** [comment]
Thanks .. with JsRuntimeAttributeDispatchSetExceptionsToDebugger set, my debug event callback is called.

What is the performance penalty for having the debugging enabled - no breakpoints but only to be able to "log" unhandled exceptions.

Thanks again

K

**Comment by rhuanjl** [comment]
I don't think `JsRuntimeAttributeDispatchSetExceptionsToDebugger` will have any noticeable performance impact. It's setting a flag that's only checked when an exception occurs and anything involving an exception is going to be a slow down point already.
