### ISSUE TITLE
-NaN

### ISSUE THREAD

**Issue by lionche** [chakra-core/ChakraCore#6879]
###### Version

chakra-1.11.24.0

###### Test case

```js
const a = Math.pow()
const b = -a
const c = b.toLocaleString();
print(c)
```

###### Execution steps

    .ch Testcase.js

###### Output
```
-NaN
```

###### Expected result
    NaN
     
###### Description

The correct output of the test case should be `NaN` while chakra yields `-NaN` . This may be caused by the incorrect implementation of chakra.

**Comment by ppenzin** [comment]
Why is this incorrect? `-NaN` is a valid "value" and in this case you are negating a "positive" `NaN`.

As an aside, sign of `NaN` is immaterial, because comparing a `NaN` to anything, including other `NaN` bit patterns, always yields false.

**Comment by ShortDevelopment** [comment]
The current `master` branch gives me the expected result of `NaN`, so it's already fixed?

**Comment by rhuanjl** [comment]
> Why is this incorrect? `-NaN` is a valid "value" and in this case you are negating a "positive" `NaN`.
> 
> As an aside, sign of `NaN` is immaterial, because comparing a `NaN` to anything, including other `NaN` bit patterns, always yields false.

I think per the spec negating a positive NaN should just return NaN and skip the negation op - which current master appears to do, so closing for now.
