### ISSUE TITLE
ubuntu20.04 Failed to compile ChakraCore1.4.1

### ISSUE THREAD

**Issue by Aligado0628** [chakra-core/ChakraCore#6933]
clang version 6.0
cmake version 3.16
Compilation error

Scanning dependencies of target Chakra.Pal
[  0%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/file.cpp.o
In file included from /home/octopus/ChakraCore-1.4.1/pal/src/cruntime/file.cpp:23:
In file included from /home/octopus/ChakraCore-1.4.1/pal/src/include/pal/palinternal.h:334:
/home/octopus/ChakraCore-1.4.1/pal/inc/pal.h:6484:22: error: definition of builtin function '_rotl'
unsigned int __cdecl _rotl(unsigned int value, int shift)
                     ^
/home/octopus/ChakraCore-1.4.1/pal/inc/pal.h:6507:28: error: definition of builtin function '_rotl64'
unsigned long long __cdecl _rotl64(unsigned long long value, int shift)
                           ^
/home/octopus/ChakraCore-1.4.1/pal/inc/pal.h:6525:22: error: definition of builtin function '_rotr'
unsigned int __cdecl _rotr(unsigned int value, int shift)
                     ^
/home/octopus/ChakraCore-1.4.1/pal/inc/pal.h:6543:28: error: definition of builtin function '_rotr64'
unsigned long long __cdecl _rotr64(unsigned long long value, int shift)
                           ^
4 errors generated.
make[2]: *** [pal/src/CMakeFiles/Chakra.Pal.dir/build.make:63：pal/src/CMakeFiles/Chakra.Pal.dir/cruntime/file.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:667：pal/src/CMakeFiles/Chakra.Pal.dir/all] error 2
make: *** [Makefile:130：all] error 2
See error details above. Exit code was 2

**Comment by Aligado0628** [comment]
In file included from /home/octopus/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:11:
In file included from /usr/include/unicode/normalizer2.h:34:
In file included from /usr/include/unicode/uniset.h:23:
In file included from /usr/include/unicode/uset.h:34:
In file included from /usr/include/unicode/localpointer.h:45:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/memory:83:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/utility:229:43: error: no matching function for call to 'move'
    { return __pair_get<_Int>::__move_get(std::move(__in)); }
                                          ^~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/move.h:101:5: note: candidate function template not viable: requires single argument '__t', but no arguments were provided
    move(_Tp&& __t) noexcept
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_algobase.h:593:5: note: candidate function template not viable: requires 3 arguments, but 0 were provided
    move(_II __first, _II __last, _OI __result)
    ^
In file included from /home/octopus/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:11:
In file included from /usr/include/unicode/normalizer2.h:34:
In file included from /usr/include/unicode/uniset.h:23:
In file included from /usr/include/unicode/uset.h:34:
In file included from /usr/include/unicode/localpointer.h:45:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/memory:83:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/utility:228:5: error: no return statement in constexpr function
    get(std::pair<_Tp1, _Tp2>&& __in) noexcept
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/utility:239:49: error: no matching function for call to 'move'
    { return __pair_get<_Int>::__const_move_get(std::move(__in)); }
                                                ^~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/move.h:101:5: note: candidate function template not viable: requires single argument '__t', but no arguments were provided
    move(_Tp&& __t) noexcept
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_algobase.h:593:5: note: candidate function template not viable: requires 3 arguments, but 0 were provided
    move(_II __first, _II __last, _OI __result)
    ^
In file included from /home/octopus/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:11:
In file included from /usr/include/unicode/normalizer2.h:34:
In file included from /usr/include/unicode/uniset.h:23:
In file included from /usr/include/unicode/uset.h:34:
In file included from /usr/include/unicode/localpointer.h:45:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/memory:83:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/utility:238:5: error: no return statement in constexpr function
    get(const std::pair<_Tp1, _Tp2>&& __in) noexcept
    ^
In file included from /home/octopus/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:11:
In file included from /usr/include/unicode/normalizer2.h:34:
In file included from /usr/include/unicode/uniset.h:23:
In file included from /usr/include/unicode/uset.h:34:
In file included from /usr/include/unicode/localpointer.h:45:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/memory:83:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:37:
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:676:69: error: expected expression
        : _Inherited(static_cast<const _Tuple_impl<0, _UElements...>&>(__in))
                                                                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:686:69: error: expected expression
        : _Inherited(static_cast<const _Tuple_impl<0, _UElements...>&>(__in))
                                                                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:696:64: error: expected expression
        : _Inherited(static_cast<_Tuple_impl<0, _UElements...>&&>(__in)) { }
                                                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:705:64: error: expected expression
        : _Inherited(static_cast<_Tuple_impl<0, _UElements...>&&>(__in)) { }
                                                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1007:64: error: expected expression
        : _Inherited(static_cast<const _Tuple_impl<0, _U1, _U2>&>(__in)) { }
                                                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1014:64: error: expected expression
        : _Inherited(static_cast<const _Tuple_impl<0, _U1, _U2>&>(__in)) { }
                                                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1021:59: error: expected expression
        : _Inherited(static_cast<_Tuple_impl<0, _U1, _U2>&&>(__in)) { }
                                                                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1028:59: error: expected expression
        : _Inherited(static_cast<_Tuple_impl<0, _U1, _U2>&&>(__in)) { }
                                                                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1035:19: error: expected expression
        : _Inherited(__in.first, __in.second) { }
                         ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1035:31: error: expected expression
        : _Inherited(__in.first, __in.second) { }
                                     ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1042:19: error: expected expression
        : _Inherited(__in.first, __in.second) { }
                         ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1042:31: error: expected expression
        : _Inherited(__in.first, __in.second) { }
                                     ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1049:37: error: expected expression
        : _Inherited(std::forward<_U1>(__in.first),
                                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1050:30: error: expected expression
                     std::forward<_U2>(__in.second)) { }
                                           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple:1057:37: error: expected expression
        : _Inherited(std::forward<_U1>(__in.first),
                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [lib/Runtime/PlatformAgnostic/Platform/CMakeFiles/Chakra.Runtime.PlatformAgnostic.dir/build.make:89：lib/Runtime/PlatformAgnostic/Platform/CMakeFiles/Chakra.Runtime.PlatformAgnostic.dir/Linux/UnicodeText.ICU.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1113：lib/Runtime/PlatformAgnostic/Platform/CMakeFiles/Chakra.Runtime.PlatformAgnostic.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
See error details above. Exit code was 2

**Comment by ppenzin** [comment]
Current version builds on 20.04

**Comment by ppenzin** [comment]
Please let me know if we can help with building a newer version (latest release should do as well).
