### ISSUE TITLE
How can I debug ch.exe ?

### ISSUE THREAD

**Issue by mosheDO** [chakra-core/ChakraCore#6969]
Hi

I'm trying to debug the ch.exe file in Visual Studio, but it crashes immediately and I couldn't find any Wiki/Tutorial on that.
is this a known issue? or there anything related to that?

Regards, Moshe

**Comment by rhuanjl** [comment]
It shouldn't crash; I'm afraid I've never used the Visual Studio debugger, @fatcerberus do you have any experience/thoughts on this?

**Comment by mosheDO** [comment]
Hi
After investigating it seems that the reason is because in the properties the debug is defined as script and not native.
Changing that will fix it.

Just out of curiosity what debugger do you use?

**Comment by rhuanjl** [comment]
I primarily develop in VSCode on a mac; I debug with GDB via the CPP add on.

**Comment by ShortDevelopment** [comment]
@mosheDO Did you get it to work?

**Comment by mosheDO** [comment]
Yes, sorry for not closing

**Comment by ShortDevelopment** [comment]
No problem!
Good to know you could solve your issue 😊

**Comment by mosheDO** [comment]
@ShortDevelopment 

Just out of curiosity is there any planning to add some new JS features such as BigInt for example?
