### ISSUE TITLE
Blaccbarbie8.ws

### ISSUE THREAD

**Issue by Blaccdoll88** [chakra-core/ChakraCore#6994]
-{"cplatform":"mobile","cff":"SMALL_FORM_FACTOR","c":"android","cplayer":"PLATYPUS","cmodel":"SM-A037U","cos":"Android","soc":"Mediatek:MT6765V\/CB","cver":"19.14.42","cbrand":"samsung","cbr":"com.google.android.youtube","csdk":"33","cbrver":"19.14.42","cosver":"13.TP1A.220624.014.A037USQU4DWG1","videoid":"WFymLBShONw","cpn":"alqnqpwmpVBW2L37","fmt":"136 avc1 720x1280@24","afmt":"251:CggKA2RyYxIBMQ opus","bh":11864,"conn":3,"volume":73,"loudness":"-3.230","bat":"0.010:1","df":"0\/111","time":"2024-04-21T09:05:25.337Z","glmode":"RECTANGULAR_2D","drm":"","mtext":"GQ:55.4s;","error":"No errors","logged_in":"1","e":"23888716,23946420,23964928,23966208,23983296,23998056,24004644,24036947,24061700,24077241,24078649,24080738,24104894,24117491,24120819,24132305,24135310,24143331,24166867,24181174,24187377,24230811,24232551,24241378,24260378,24265964,24267186,24271689,24290971,24377598,24384759,24397985,24406318,24451319,24455312,24458317,24458329,24458684,24468724,24475157,24515423,24522874,24524098,24542367,24545210,24548465,24548627,24548629,24555431,24556101,24560416,24562015,24569425,24585133,24585737,24690006,24697069,39325413,39325972,39325978,39326126,51009781,51010008,51012659,51016856,51017346,51020570,51021185,51023529,51024556,51024714,51025415,51030103,51033399,51033491,51033765,51034627,51035173,51037344,51037349,51038803,51040842,51041280,51046127,51048236,51048489,51050361,51052868,51053477,51053689,51054999,51057842,51057851,51058424,51058725,51059571,51060353,51063048,51063581,51064835,51067700,51068313,51068632,51069269,51071073,51074183,51079239,51079317,51080128,51080264,51081684,51083716,51084521,51085008,51089177,51089441,51090385,51092660,51092992,51094171,51094202,51094207,51095478,51096153,51098777,51100401,51101454,51101504,51102344,51103858,51106995,51107336,51108006,51108109,51111738,51112401,51113658,51113663,51115164,51115184,51116067,51116254,51117318,51118932,51119651,51120238,51120276,51120722,51123073,51124104,51124405,51124412,51124477,51125857,51125901,51127504,51128585,51129105,51129208,51129209,51129558,51131376,51131840,51132393,51132529,51132535,51134883,51134885,51135652,51136218,51136253,51136811,51136997,51137045,51139379,51139566,51141767,51141798,51141867,51142886,51142889,51142973,51144818,51144925,51145437,51145749,51145947,51146737,51146962,51147554,51147838,51148976,51148983,51149422,51150926,51152043,51152050,51152100,51152207,51152396,51152831,51152842,51152918,51153542,51154012,51154816,51156462,51157411,51157838,51158470,51158514,51158534,51161119,51162170,51162384,51162876,51163083,51163639,51163760,51164910,51165696,51165738,51165740,51166648,51167063,51167143,51167169,51168225,51170373,51171972"}

**Comment by ShortDevelopment** [comment]
@Blaccdoll88 I see you're new to GitHub. This is the ChakraCore (a javascript engine) repository.
Do you have an issue related to ChakraCore?

**Comment by fatcerberus** [comment]
Pretty sure it's just a spambot.

**Comment by ppenzin** [comment]
"Close as spam" :smile:
