### ISSUE TITLE
[Build]: When did ChakraCore start supporting compilation for ARM on Linux?

### ISSUE THREAD

**Issue by smithjiang** [chakra-core/ChakraCore#6997]
### Operating System

jp master

### Compiler

jp master

### ChakraCore Version

jp master

### Compiler output

```shell
When did ChakraCore start supporting compilation for ARM on Linux?
```

### Additional Context

When did ChakraCore start supporting compilation for ARM on Linux?

**Comment by ppenzin** [comment]
Duplicate of #6468, #6335

**Comment by ppenzin** [comment]
(now with correct status)
